### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by swalahamani** [ricmoo/aes-js#103]
Hi, Is this repo still maintained? Can I use this safely?

**Comment by ricmoo** [comment]
Yes, this library is still maintained, but I haven’t done much too it in quite some time.

I am planning a major version bump at some point in the near-ish future, and contemplating merging it into my @ethersproject mono repo, but still not sure of that yet. I’d open an issue on this repo to discuss that last point before I do.

**Comment by swalahamani** [comment]
Thank you, Richard, for the update.
