### ISSUE TITLE
Encrypt CBC padding 7 is different from Java

### ISSUE THREAD

**Issue by NguyenVanCong1902** [ricmoo/aes-js#114]
I'm trying to encrypt CBC mode padding 7 with this Library then comparing with Java. But Encrypt Result is not same

IV: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
Key: 00001111222233334444555566667777
Mode: CBC Padding 7

**Javascript**
```
    function encryptTest(){
        let iv = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16];
        
        let keyBytes = aesjs.utils.utf8.toBytes('00001111222233334444555566667777');
        
        // Convert text to bytes with padding 7
        let textBytes = aesjs.padding.pkcs7.pad(aesjs.utils.utf8.toBytes('TEST_STRING'));
        
        let aesCbc = new aesjs.ModeOfOperation.cbc(keyBytes, iv);
        let encryptedBytes = aesCbc.encrypt(textBytes);
        console.log(Array.from(encryptedBytes));
        // ressult: [23, 92, 106, 148, 133, 112, 123, 116, 227, 175, 47, 145, 105, 179, 205, 114]
    }
```

**Java**
```
    public static void encryptTest() throws Exception {
        byte[] iv = new byte[]{1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16};//generateIv();
        Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5PADDING"); // java use padding 5 same as padding 7

        SecretKeySpec keyspec = new SecretKeySpec("00001111222233334444555566667777".getBytes("UTF-8"), "AES");
        IvParameterSpec ivspec = new IvParameterSpec(iv);

        cipher.init(Cipher.ENCRYPT_MODE, keyspec, ivspec);
        byte[] encryptedBytes = cipher.doFinal("TEST_STRING".getBytes("UTF-8"));

        System.out.println(Arrays.toString(encryptedBytes));
        //ressult: [23, 92, 106, -108, -123, 112, 123, 116, -29, -81, 47, -111, 105, -77, -51, 114]
    }
```

I don't now what is wrong here 😵‍💫

**Comment by ricmoo** [comment]
Are you sure your key is **UTF-8** bytes? The above key would be `[ 0x30, 0x30, 0x30, 0x30, 0x31, 0x31, 0x31, 0x31, and_so_on ]`.

The UTF-8 value of the character `"0"`is 0x30 (or 48).

That is my first guess. Let me know if you already accounted for that.

**Comment by ricmoo** [comment]
Oh. Actually, reading more you got the same result, except it looks like Java returns signed bytes. Just add 256 to all negative values. :)

**Comment by NguyenVanCong1902** [comment]
> Oh. Actually, reading more you got the same result, except it looks like Java returns signed bytes. Just add 256 to all negative values. :)

Oh, awesome, i got it. Thank you. Then, how can i use signed bytes when encrypting with javascript? I'm encrypting with javascript then decrypting at Backend Java

**Comment by NguyenVanCong1902** [comment]
```
function signed_Int8(value) {
	let ref = value & 0xFF;
	return (ref > 0x7F) ? ref - 0x100 : ref;
};
```
i used this function to convert to sign integer array. Now, Encrypt Result is same. Tysm 😘😘😘

**Comment by ricmoo** [comment]
You could do that, but that is a lot of overhead, math and code.

A Typed Array (Like an Int8Array) is just an access container on top of an under-lying buffer, which is just a bunch of raw bytes. So you just need to create an unsigned access container:

```
// This is what you stared with:
int8 = new Int8Array([ 23, 92, 106, -108, -123, 112, 123, 116, -29, -81, 47, -111, 105, -77, -51, 114 ])

// Just use the same `buffer`, this means no additional space is required, it will reuse the
// int8 buffer above, it just changes how the contents are interpreted when you access them...
uint8 = new Uint8Array(int8.buffer)
// Uint8Array { 23, 92, 106, 148, 133, 112, 123, 116, 227, 175, 47, 145, 105, 179, 205, 114 }
```

Hope that helps. See [Typed Arrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays)

**Comment by NguyenVanCong1902** [comment]
> You could do that, but that is a lot of overhead, math and code.
> 
> A Typed Array (Like an Int8Array) is just an access container on top of an under-lying buffer, which is just a bunch of raw bytes. So you just need to create an unsigned access container:
> 
> ```
> // This is what you stared with:
> int8 = new Int8Array([ 23, 92, 106, -108, -123, 112, 123, 116, -29, -81, 47, -111, 105, -77, -51, 114 ])
> 
> // Just use the same `buffer`, this means no additional space is required, it will reuse the
> // int8 buffer above, it just changes how the contents are interpreted when you access them...
> uint8 = new Uint8Array(int8.buffer)
> // Uint8Array { 23, 92, 106, 148, 133, 112, 123, 116, 227, 175, 47, 145, 105, 179, 205, 114 }
> ```
> 
> Hope that helps. See [Typed Arrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays)

Awesome, clear and understandable. I have not worked with Typed Arrays before, now i got it 😘😘
