### ISSUE TITLE
Not the same output when not using Buffer class.

### ISSUE THREAD

**Issue by RaedsLab** [ricmoo/aes-js#12]
The output of the CBC mode encryption different when the [condition](https://github.com/ricmoo/aes-js/blob/f4e9eba001b556179fba978288cd1d7714fc9dfa/index.js#L39 ) `if (typeof(Buffer) === 'undefined')` changes. 

I'm not really sure if this is the expected behavior ?

**Comment by ricmoo** [comment]
Hey ReadsLab,

Can you provide a quick example?

**Comment by RaedsLab** [comment]
Backstory : I'm trying to use aes-js in an [environment ](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey) that doesn't have a "Buffer" class.

```node
var const_Zero = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];
var aesCbc = new aesjs.ModeOfOperation.cbc(const_Zero, const_Zero);
var encryptedBytes = new Uint8Array();
encryptedBytes = aesCbc.encrypt(const_Zero);
console.log(encryptedBytes);
```
running this in node (a.k.a Buffer is defined) outputs:
`<Buffer 66 e9 4b d4 ef 8a 2c 3b 88 4c fa 59 ca 34 2b 2e>`

Otherwise it outputs : 
`[ 102, 233, 75, 212, 239, 138, 44, 59, 136, 76, 250, 89, 202, 52, 43, 46 ]`

Is this reproducible ?

**Comment by RaedsLab** [comment]
My bad, this is _coffeeless-morning _mistake of my part ^^' 

Thank you for your time and sorry for the inconvenience.

**Comment by ricmoo** [comment]
No worries. :)
