### ISSUE TITLE
Inconsistent error formats

### ISSUE THREAD

**Issue by togakangaroo** [ricmoo/aes-js#15]
When new-ing up `aesjs.ModeOfOperation.cfb` passing an incorrect length of key throws an error. However passing an incorrect iv length returns some sort of error object. It should throw an error also.

**Comment by ricmoo** [comment]
I will look more into this on the weekend, but yes, I agree, things should be consistent.

**Comment by ricmoo** [comment]
Hey @togakangaroo,

Sorry this took so long. It is now fixed, with 299 additional test cases to check for invalid parameters and make sure they throw proper exceptions. The changes are available in v2.0.0;

https://github.com/ricmoo/aes-js/releases/tag/v2.0.0

Thanks, and please let me know if you find any other issues.
