### ISSUE TITLE
Encryption mode: SIV

### ISSUE THREAD

**Issue by stanleyxu2005** [ricmoo/aes-js#21]
Is it possible to encryption with SIV mode (RFC 5297)?

**Comment by ricmoo** [comment]
I do not natively support it in the library, but it should "not be difficult" (TM) to implement as an external library. The AES Block Cipher, Counter and CTR mode are all available. :)

The optimization recommended in section 5 is certainly not necessary, as the counter operates on bytes.

If you are interested in creating it, you should simply create an NPM package which pulls in aes-js and implement section 2.6 and section 2.7 in the RFC, put some test cases together (along with the test vectors in Appendix A) and I will add a link to it in my README.md.

**Comment by stanleyxu2005** [comment]
Fair enough
