### ISSUE TITLE
How to encrypt XML

### ISSUE THREAD

**Issue by planetwebsolution** [ricmoo/aes-js#27]
I am having a `XML` and I need to encrypt with one time session key. I tried many ways but when I pass `new aesjs.ModeOfOperation.ecb('32 bit encrypted string');` it did not work. So I am confused in session key. If I pass `XML` as `textBytes = aesjs.utils.utf8.toBytes(text);` and try to encrypt I got this error `invalid plaintext size (must be multiple of 16 bytes)`. Will you please share your suggestion ? Here is my demo XML which I want to encrypt with one time session key. 

````
<?xml version="1.0"?>
<root>
  <xmlbuilder>
    <repo type="git">git://github.com/oozcitak/xmlbuilder-js.git</repo>
  </xmlbuilder>
</root>
````

**Comment by ricmoo** [comment]
What do you mean by "32 bit encrypted string"? The key must be a 16, 24 or 32 byte array.

There are 5 modes of operation. The ECB mode requires the input string to be a multiple of 16 bytes, so you can use PKCS#7 padding:

```javascript
var xml = 'some data';
var data = aesjs.utils.utf8.toBytes(xml);
var paddedData = aesjs.padding.pkcs7.pad(data);
var encryptedData = aes.encrypt(paddedData);
var hexEncryptedData =aesjs.utils.hex.fromBytes(encryptedData);
console.log(hexEncryptedData);
```

Please keep in mind the ECB method of encryption can leak patterns in data. For example, analysis of a large encrypted XML document may reveal the fact it is an XML document.

I would recommend you use the CTR method, which also does not require any padding be done.

Make sense? Let me know if you have any problems.

Thanks!
RicMoo

**Comment by ricmoo** [comment]
Are there any further questions or concerns with this issue? Otherwise, I will close it.

Thanks,
RicMoo

**Comment by Ruffio** [comment]
@ricmoo I think that this can be closed now...

**Comment by Ruffio** [comment]
@ricmoo I think that this can be closed now...

**Comment by ricmoo** [comment]
Thanks!
