### ISSUE TITLE
Padding question

### ISSUE THREAD

**Issue by aakilfernandes** [ricmoo/aes-js#28]
Hi,

I have a quesion about how padding works in CBC mode (128bit). If I have a 128bit plain text, will padding increase the size to 256bits? I believe this is how it works in node's crypto library when `autopadding` is left on.

If the size is increased, is there any way to turn padding off?

**Comment by ricmoo** [comment]
Heya!

CBC requires the ciphertext (and plaintext) be a multiple of the block size, which is 16 bytes (128 bits), so without padding, 128-bits would fit in a block, and would not not need padding.

PCKS#7 will always add a full block of 0x10 (decimal 16) bytes to the end of input that is exactly a multiple of the block size.

So, for example, with PKCS#7 and CBC:

0 bytes => 16 bytes
1 byte => 16 bytes
2 byte => 16 bytes
...
14 bytes => 16 bytes
15 bytes => 16 bytes
16 bytes => 32 bytes
17 bytes => 32 bytes

Padding in `aesjs` is entirely opt-in, by default it does nothing (and will throw an error if you pass in input with an inappropriate size). So, you should not be seeing any size increase unless you are manually padding; 16 bytes in should result in 16 bytes out.

Let me know if you need any more clarification, and feel free to post code snippets or links to gists.

Thanks,
RicMoo

**Comment by aakilfernandes** [comment]
That makes perfect sense. Thanks!
