### ISSUE TITLE
Angular 2 implementation

### ISSUE THREAD

**Issue by zmanring** [ricmoo/aes-js#30]
Maybe I am confused.. How do I take a string `"jahsdf"` and make it 16 byte so that I can encrypt it? I am using the CBC encryption and I am stuck converting my password to 16 byte. Any help would be much appreciated! I am getting a `invalid plaintext size (must be multiple of 16 bytes)`

**Comment by ricmoo** [comment]
Heya zmanring!

This is touched on a little in the [Keys section](https://github.com/ricmoo/aes-js#keys) of the readme, but I should probably expand it more.

There are many ways to do this, with various levels of security. The class of algorithms that do this are called "Password-Based Key Derivation Functions" (PBKDF). You can so something simple, such as SHA2 or SHA3 hash the string, which will produce a key, but this method is subject to [Rainbow Attacks](https://en.wikipedia.org/wiki/Rainbow_table).

Common options for this include:
- pbkdf2 [on NPM](https://www.npmjs.com/package/pbkdf2)
- scrypt; which is an algorithm intentionally expensive to prevent brute force attacks. I have an implementation [on NPM](https://www.npmjs.com/package/scrypt-js).
- Other options include crypt and bcrypt

The important thing is that you use a cryptographically strong way to expand a password into a key, which is what the above algorithms provide. You should also make sure to take [UTF-8 encoding](https://github.com/ricmoo/scrypt-js#encoding-notes) into account.

**Comment by Ruffio** [comment]
Hasn't this 'issue' been resolved? On the frontpage there are some good description of this IMHO...

**Comment by Ruffio** [comment]
@zmanring Can this be closed?

**Comment by Ruffio** [comment]
@ricmoo this issue should be closed to lack of response from @zmanring ...

**Comment by ricmoo** [comment]
Yes, closing this now. If there are any further issues, please feel free to re-open. :)

Thanks! :)
