### ISSUE TITLE
Embedded Licence into js

### ISSUE THREAD

**Issue by chan493** [ricmoo/aes-js#32]
Please include licence remark into js.

**Comment by ricmoo** [comment]
You mean place the contents of the MIT license into the actual JS files?

The license is indicated in the license.txt and the package.json, but I can certainly embed the content into the top of the JavaScript file; just out of curiosity, why is this necessary?

I will get around to this next week, and create a gruntfile to create a minified version.

**Comment by chan493** [comment]
Sorry for misunderstanding. I mean place the contents of extra information (author, copyright, js download path, etc.) into js files.

Here is one of the example:
/*
 * JavaScript MD5
 * https://github.com/blueimp/JavaScript-MD5
 *
 * Copyright 2011, Sebastian Tschan
 * https://blueimp.net
 *
 * Licensed under the MIT license:
 * https://opensource.org/licenses/MIT
 *
 * Based on
 * A JavaScript implementation of the RSA Data Security, Inc. MD5 Message
 * Digest Algorithm, as defined in RFC 1321.
 * Version 2.2 Copyright (C) Paul Johnston 1999 - 2009
 * Other contributors: Greg Holt, Andrew Kepert, Ydnar, Lostinet
 * Distributed under the BSD License
 * See http://pajhome.org.uk/crypt/md5 for more info.
 */

**Comment by Ruffio** [comment]
Maybe this can come in next build?

**Comment by ricmoo** [comment]
I've placed a small marker at the top with basic info and a reference to the license.txt.

Thanks! :)
