### ISSUE TITLE
fromBytes optimization

### ISSUE THREAD

**Issue by felipemanga** [ricmoo/aes-js#33]
Hello,

I noticed that utf8.fromBytes creates an array of strings and later on joins them.
At least on my Windows machine, running the latest chrome, it is _much_ faster to simply do the "naive" thing and concat strings together. I assume it also uses much less memory, but I didn't profile that. I've been testing with strings that are a bit over 12MB long, and the difference is noticeable (from over 10s to <1s).

Also, using array.push(value) is really slow compared to doing array[array.length] = value;

This is probably not a problem in the general use-case, but it might have a significant impact on projects that run on mobiles, due to the slower CPUs and smaller RAM.

    function toStr(bytes){
        var result = "", i = 0, l = 0, max = bytes.length;
        while (i < max) {
            var c = bytes[i];
            if (c < 128) {
                result += String.fromCharCode(c);
                i++;
            } else if (c > 191 && c < 224) {
                result += String.fromCharCode(((c & 0x1f) << 6) | (bytes[i + 1] & 0x3f));
                i += 2;
            } else {
                result += String.fromCharCode(((c & 0x0f) << 12) | ((bytes[i + 1] & 0x3f) << 6) | (bytes[i + 2] & 0x3f));
                i += 3;
            }
        }
        return result;
    }

**Comment by agol** [comment]
Here's a simple test to compare the performance of various string concatenation methods:
https://jsperf.com/join-concat/2

**Comment by ricmoo** [comment]
That is pretty crazy. I will try out changing this soon; I've been busy trying to close out another project, which I should be able to launch next week, then I can focus on getting some of the extra features, performance improvements and benchmarks done for some of my libraries.

The string concatenation is about 26% faster, which is completely backward to Python, but interesting.

Thanks!

**Comment by Ruffio** [comment]
@felipemanga nice finding :-) I'm building a service that should also run on mobile devices, so RAM/CPU footprint is definitely interesseting from my perspective.

**Comment by Ruffio** [comment]
@ricmoo did you have a change to try this out?

**Comment by ricmoo** [comment]
Sorry, I haven't. I'm spending a little time catching up on some of these projects. I will try to get to this sooner than later.

**Comment by Ruffio** [comment]
Just ran the jsperf test three times in differrent browsers. Interesting to see how the browsers handle the tests. The gain in Edge is insane...

![image](https://user-images.githubusercontent.com/1877612/30849517-e3841bee-a2a2-11e7-970c-ea1a374b83ab.png)

![image](https://user-images.githubusercontent.com/1877612/30849559-018ffda6-a2a3-11e7-9fac-5fdc3589d2cb.png)

![image](https://user-images.githubusercontent.com/1877612/30849580-14853c8c-a2a3-11e7-91bd-f1cafc980871.png)

![image](https://user-images.githubusercontent.com/1877612/30849599-24e4aba8-a2a3-11e7-9af5-ca66f4c31c5a.png)

**Comment by Ruffio** [comment]
@felipemanga Why don't you provide a PR on this?

**Comment by ricmoo** [comment]
The utf-8 coder will be going away in the next version anyways, there are plenty of more advanced UTF-8 libraries (not to mention many platforms, such as node have native implementations built-in), so it doesn't make sense to bloat the AES block cipher with them.

I'm going to close this, and will try to get the new version up soon, written in TypeScript, compiled to JavaScript for the list version. Please feel free to re-open or make further suggestions (I monitor closed tickets).

Thanks! :)
