### ISSUE TITLE
Object function ArrayBuffer() { [native code] } has no method 'isView'

### ISSUE THREAD

**Issue by clarklight** [ricmoo/aes-js#34]
I am using the aes.js on a phonegap app, and this appeared on 1 version of android. I am wondering if you would have any idea what this means? 

Object function ArrayBuffer() { [native code] } has no method 'isView'

Thanks !

**Comment by ricmoo** [comment]
What version of Android are you using and what version of aes-js?

In aes-js v3.0.0 and above, I moved to using Tuped Arrays, which are much faster, but not fully supported in older browsers.

If that is the case, v2 might work better. But let me know what version and if I can reproduce it, I can try fixing it in v3.

**Comment by clarklight** [comment]
Thanks for the quick reply, using the latest version, tested on android 4.4 the problem occurs on aes.js line 24. Thanks!

And 1 quick question, if i need version 2, how do i get a version of that. Thanks!

**Comment by ricmoo** [comment]
How are you including it? If you use npm, just add "aes-js": "^2.0.0" to the packages.json.

If you are including it in a script tag, you should be able to find a tag the download from. I'm out right now,  it when I get back, I can find the exact link for you.

I need to be able to reproduce it, since I will have to implement some alternative to isView.

**Comment by clarklight** [comment]
I am including it in a script tag. I will try to find a link to download from for the time being. Take your time, when you are free later on please include the link for me. Thanks! 

If there is anything i can help let me know.

**Comment by clarklight** [comment]
I tried the v2 and v2.1 but this error popped up. Not sure if i am doing something wrong.  Cannot read property 'utf8' of undefined

**Comment by arrmii** [comment]
Same issue on Debian Jessie. Added  "aes-js": "^2.0.0" to packages,json, no success. This is my .js:

#!/usr/bin/env node

"use strict";

var lora = require('lora-decrypt');
var payload_hex = '288CCB72C4EB1FEA9EAD7E149088CCD3';
var sequence_counter = 2;
var key = '2b7e151628aed2a6abf7158809cf4f3c';
var addr = '0100200E';
lora.lora_decrypt(payload_hex, sequence_counter, key, addr);

**Comment by Ruffio** [comment]
It looks like that not all browsers has this method implemented and therefore throws an exeception.
This for example is not implemented in IE 10 and previous versions: https://docs.microsoft.com/en-us/scripting/javascript/reference/arraybuffer-isview-function-arraybuffer

I also found this Stackoverflow with a substitution implementation. Maybe that implementation could be used instead? https://stackoverflow.com/questions/21753581/check-for-an-instance-of-arraybufferview

Here is a description of what isView is used for: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer

Would it be possible to use some kind of feature detection to use the .isVew with the above implementation as fallback?

**Comment by ricmoo** [comment]
This check was largely unnecessary, so it has been removed.

Thanks! Let me know if there are any other issues. :)
