### ISSUE TITLE
Calculate the Counter value given the offset into the ciphertext

### ISSUE THREAD

**Issue by CervantesVive** [ricmoo/aes-js#35]
Thanks for providing this library @ricmoo , I am finding this very useful.

_How do I calculate the counter given an offset into the cipher text?_

I know the initial counter used for encryption.
I have a partial ciphertext and I know the byte offset into the complete cipher text.

Looking through the sources at how the counter is incremented as the decrypt takes place seemed that it should be straight forward but trying a simple test does not show the plaintext.

Here is what I have been trying (simplified)
- I encrypted the package.json file at the root of your project using python
- verified the entire file can be decrypted using your lib w a counter of 0
- Tried to read the encrypted file at an offset then decrypting using the same procedure but incrementing the initial counter depending on the byte offset like below. This did not work.

```
var bytesToRead = 500;
var fileOffset = 200;
var val = fileOffset / 16;
var counter = new aesjs.Counter(0);
while (val > 0) {
  val--;
  counter.increment();
}

var key = new Buffer(options.key);
var ciphertextFile = path.resolve(__dirname, 'package.json.enc');
var decrypter = new aesjs.ModeOfOperation.ctr(key, counter);
fs.open(ciphertextFile, 'r', function(status, fd) {
  var buffer = new Buffer(bytesToRead);
  fs.read(fd, buffer, 0, bytesToRead, fileOffset, function() {
    var padded = aesjs.padding.pkcs7.pad(buffer);
    var plaintext = decrypter.decrypt(padded);
    var text = aesjs.utils.utf8.fromBytes(plaintext);
    console.log('decrypted text: ', text);
  });
});
```

**Comment by ricmoo** [comment]
So, I haven't tried out your code yet, just pointing out a few things... If it doesn't help, let me know and I will look more into it:

Your offset of 200 is not congruent to 0 mod 16, so later when you jump into the file at offset 200, you are running the one-time pad against the wrong section.

Also, CTR does not require any padding, so padding it might lead to weird goo at the end of the decrypted output.

I don't see where bytesToRead is set either.

Just a few ideas. Let me know if there are still issues. But something *like* this should certainly work.

**Comment by CervantesVive** [comment]
Thank you for your reply.

I accidentally introduced some errors when I copied the code. I think I've corrected them.

I thought the padding was necessary to align the fragment to 16 bytes since the offset is an arbitrary location into the ciphertext. The padding will add the weird goo to the plaintext but I can trim afterwards and the rest should be good.

Or does the decryption only works on complete 16 byte block so I cannot decrypt at a random offset?

**Comment by ricmoo** [comment]
The decryption must begin on 16 byte block, but you could easily throw junk in and strip it. For examples (this is in pseudo code, off the top of my head):

```
var data = utils.toUtf8Bytes([ 200 bytes ] + "A B C D ");
```

if you only cared about the `A B C D`, you could decrypt using something like:

```
// Skip the counter forward to where you want to begin
var counter = new Counter(Math.floor(200 / 16));

// Create the AES mode of operation
var decrypter = new AESCounterMode(key, counter);

// Eat up the offset number of bytes you want to ski[
var junk = utils.toUtf8Bytes("JUNKJUNKJUNKJUNK");
decrypter.decrypt(junk.slice(0, 200 % 16));

// Now the internal state has the counter properly aligned to the block and byte within the block
var plaintext = decrpyter.decrypt(data.slice(200))
```

Kinda complicated though. Might be easier to just start decryption from the correct block and trim it off.

Does that make sense? I recommend checking out [this wikipedia page](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation) to see how these work, internally.

**Comment by CervantesVive** [comment]
In my case I do not have access to the entire ciphertext, only a fragment and the offset. In some cases it can be the last few K of a multi-meg file.

Thank you for the link, will read up further on it. Any additional help is appreciated.

**Comment by ricmoo** [comment]
So, in that case, the above method will work. You will fast-forward the counter to the Math.floor(offset / 16) block, then decrypt (offset % 16) of junk to fast-forward to the byte, and then you can just decrypt the cipher text normally.

**Comment by CervantesVive** [comment]
ok, thank you for the level of detail @ricmoo .

One last question, are there any shortcuts to fast forward to the byte w/o having to decrypt junk? 

In the case of a large ciphertext would be great to avoid creating the junk bytes into the offset.

**Comment by ricmoo** [comment]
You would never have to fast forward past more than 15 bytes of junk. Fast forwarding the counter gets you past 16 bytes at a time, and you don't need to increment, just jump. To fast-forward to byte 200 you would initialize the counter to 12 (Math.floor(200 / 16)) (which has now skipped 192 bytes) and then decrypt 8 bytes of junk, getting you to the offset of 200 in the one-time pad.

**Comment by CervantesVive** [comment]
Thanks for the help! It is all working as described now.
