### ISSUE TITLE
How to check validation for a encrypted data?

### ISSUE THREAD

**Issue by bhupendra-nitt** [ricmoo/aes-js#38]
I want to check if the data which I need to decrypt is already encrypted or not.

**Comment by ricmoo** [comment]
Depending on your purposes, this can only be done at the application data.

**Any** sequence of bytes is valid as both encrypted data and decrypted data, so there is no way to determine this solely from the data.

One option, if you have control over the data and its state is you use a checksum or MAC. For example, you could store a sha256 hash of the unencrpyted data as a prefix. If the first 32 bytes do not equal the hash of the rest of the data, you know the data is encrypted (or decrypted with the wrong password).

If you always expect the plaintext to be JSON, you can trivially check the data is valid.

Most likely, AES is too low-level for this type of detection. You need to layer additional primitives on top of your protocol to achieve this.

Does that make sense?

**Comment by bhupendra-nitt** [comment]
I have JSON, so I will be able to do the check. Thanks for the suggestion.
