### ISSUE TITLE
Key creation out of String is not clear

### ISSUE THREAD

**Issue by sylverg** [ricmoo/aes-js#39]
I would like to create the key out of a String that I am getting from server side.
The key is constructed in java : byte[] raw = new sun.misc.BASE64Decoder().decodeBuffer(keyStr); 
The JavaScript now accepts a var key = [....], however how to translate the java version to a key accepted on aes-js?

**Comment by ricmoo** [comment]
You will likely want to use a base64 decoding library. I am still debating whether to include a base64 coder in the utils, as it is a common use case, but often there are existing libraries available.

Are you using node.js? Or have the SlowBuffer available? If so, the Buffer object already supports base64 conversion.

**node.js:**
```
> a = new Buffer([1, 2, 3])
<Buffer 01 02 03>
> a.toString('base64')
'AQID'
> new Buffer('AQID', 'base64')
<Buffer 01 02 03>
```

**Browser**:
```
> btoa('\01\02\03')
< "AQID"
> atob('AQID')
< "\01\02\03"
```

**Comment by sylverg** [comment]
I am trying to impelement a decryption that is done on the new Salesforce.com lighting interface. This is an Aura environment. The issue is currently that i can not find a way to get a key representation that is "multitude of 16 bytes". In a java version, a 24 char key is fed in the standard Java library to base64decode.decodebuffer and that is accepted after you puch is through SecretKeySpec. However on the JavaScript realm there seems to be a gap not having nodejs, ... available. Your atob is possible, however returns "no multitude of 16" issue.
So something internally is done on the java side that is not done the same way on javascript between atob and your library key.

**Comment by sylverg** [comment]
with the encrypted version, based on allowing in the encryption the signed byta array, I now get on the JavaScript side:
[186, 172, 108, 98, 188, 21, 126, 22, 109, 193, 210, 5, 85, 252, 137, 29, 166, 18, 238, 154, 63, 207, 211, 40, 200, 23, 70, 26, 186, 23, 9, 220]
on the Java side I get the signed version of this Byte Array
[-70, -84, 108, 98, -68, 21, 126, 22, 109, -63, -46, 5, 85, -4, -119, 29, -90, 18, -18, -102, 63, -49, -45, 40, -56, 23, 70, 26, -70, 23, 9, -36]
This means that actually there is progress. 
I now need to convert this to the same String version. 
On the Java side I am using sun.misc.BASE64Encoder().encode(enc).

**Comment by Ruffio** [comment]
I guess the difference is signed vs. unsigned? You see the difference is
256 when there is a negative number/value?


Den 4. sep. 2017 22.39 skrev "SilverG" <notifications@github.com>:

**Comment by ricmoo** [comment]
There is only one AES standard. There are multiple modes of operation though, maybe this is what you are encountering in the different online tools? Or perhaps the padding method (cipher stealing vs. PKCS#7)

The above array is equal if you ignore the signs and just take the twos-compliment. Is there no unsigned byte array in Java? 

In Base64 though, the signs do not matter since Base64 is a binary encoding, and does not have signs. The signs only happen once you decode into values. You should not need to modify the aes-js library.

Are you trying to decode the base64 data in a browser? Or in node?

For browsers, you can simply do something akin to:

```javascript
var output = [];
var bytes = atob('AQID');
for (var i = 0; i < bytes.length; i++) {
    output.push(s.charCodeAt([i]));
}
```

For node, you can simply use:

```javasctipt
var output = new Buffer('AQID', 'base64');
```

**Comment by sylverg** [comment]
In the last version, I now can encrypt the value to the same result as the one I am getting on Java ECB.
I just need to avoid the pwd base64 encoding and change the aes js library to accept signed byte array (no check on <0, later on if I find a way to base64 encode decently i can drop changing the aes js of course).

var key = [12, -45, ....];
var value = 'toEncrypt';
var valueAsBytes = aesjs.utils.utf8.toBytes(value);
var paddedData = aesjs.padding.pkcs7.pad(valueAsBytes);
var aesEcb = new aesjs.ModeOfOperation.ecb(key);
var encryptedBytes = aesEcb.encrypt(paddedData);        
var base64String = helper.arrayBufferToBase64(encryptedBytes);

where helper contains 
    arrayBufferToBase64 : function (str){
    
        var binary = '';
        var bytes = new Uint8Array( str );
        var len = bytes.byteLength;
        for (var i = 0; i < len; i++) {
            binary += String.fromCharCode( bytes[ i ] );
        }
        return window.btoa( binary );
    }

For decrypting, I however now really need to get a base64 encoding that represents the one in Java.
So "hello world" needs to translate to 
[14, -29, 35, 54, -34, -104, -114, -123, -113, -21, -46, 120, 116, -79, -128, 33]
or the unsigned version of it.

**Comment by sylverg** [comment]
OK, all working now.

so using the functions

```
    arrayBufferToBase64 : function (str){
        var binary = '';
        var bytes = new Uint8Array( str );
        var len = bytes.byteLength;
        for (var i = 0; i < len; i++) {
            binary += String.fromCharCode( bytes[ i ] );
        }
        return window.btoa( binary );
    },
    base642ArrayBuffer : function (str){
        var binary_string = window.atob(str);
	    var len = binary_string.length;
	    var bytes = new Uint8Array(len);
    	for (var i = 0; i < len; i++)        {
        	bytes[i] = binary_string.charCodeAt(i);
    	}
    	return bytes;
	}   
```

makes that i can do the encryption/decryption with teh method 

```
	doDecrypt : function(component, event, helper) {

             var origKey = 'base64encodedkey';
             var key = helper.base642ArrayBuffer(origKey);
             var value = 'encrypted stuff';
        
             var valueAsBytes = helper.base642ArrayBuffer(value);
             console.log('valueAsBytes : ', valueAsBytes);        

             var aesEcb = new aesjs.ModeOfOperation.ecb(key);
             var decryptedBytes = aesEcb.decrypt(valueAsBytes); 
        
	     var decryptedText = aesjs.utils.utf8.fromBytes(decryptedBytes);
             console.log('decrypt result : ',decryptedText);
	},    
	doEncrypt : function(component, event, helper) {
             var origKey = 'base64encodedkey';
             var key = helper.base642ArrayBuffer(origKey);

             var value = 'securitypentestuser';
             var valueAsBytes = aesjs.utils.utf8.toBytes(value);
             var paddedData = aesjs.padding.pkcs7.pad(valueAsBytes);
             console.log('paddedvaluebyte : ',paddedData);

             var aesEcb = new aesjs.ModeOfOperation.ecb(key);
             var encryptedBytes = aesEcb.encrypt(paddedData);        

             var base64String = helper.arrayBufferToBase64(encryptedBytes);
             console.log('encrypt result : ',base64String);
        
        return base64String;
	}
```

**Comment by ImJCabus** [comment]
Thanks for posting your solution. It works for me.

But I cannot resist the urge to pull out my eyes seeing your method names dude:
`base642ArrayBuffer` is just heavy. Why would you replace 'To' with a numerical '2'?? You're headed for so much maintainability pain down the road.... btw: `arrayBufferToBase64` has a 'To' in it. What? 

Sorry, this is just something you cannot leave uncommented when your mind is set to writing 'clean' code. 😆

**Comment by Ruffio** [comment]
@sylverg so this issue can be closed?

**Comment by sylverg** [comment]
yes, can be closed


________________________________
Van: Rasmus Christiansen <notifications@github.com>
Verzonden: woensdag 13 september 2017 13:43
Aan: ricmoo/aes-js
CC: SilverG; Mention
Onderwerp: Re: [ricmoo/aes-js] Key creation out of String is not clear (#39)


@sylverg<https://github.com/sylverg> so this issue can be closed?
