### ISSUE TITLE
Can I read a file than decrypt it?

### ISSUE THREAD

**Issue by LJC0915** [ricmoo/aes-js#42]
I need to decrypt a file.

I read a video file as a string.

Do I need to turn it base64 or other formats?

```javascript
    var key = aesjs.utils.utf8.toBytes('qe$sg#oin*@Znm*X');
    var textBytes = aesjs.utils.utf8.toBytes(datastr);
    var aesEcb = new aesjs.ModeOfOperation.ecb(key);
    var decryptedBytes = aesEcb.decrypt(textBytes);
    var decryptedText = aesjs.utils.utf8.fromBytes(decryptedBytes);
    console.log(decryptedText);
```

**Comment by ricmoo** [comment]
You should use a Password-Based Key Derivation Function.

Are you using node.js or in a browser?

If you are using node, look into the [pbkdf2 function](https://nodejs.org/dist/latest-v6.x/docs/api/crypto.html#crypto_crypto_pbkdf2sync_password_salt_iterations_keylen_digest):

```javascript
var crypto = require('crypto');
var key = crypto.pbkdf2Sync('qe$sg#oin*@Znm*X', 'salt', 100000, 16, 'sha512');
```

**Comment by ErrolLin** [comment]
I use this
```
var key = aesjs.utils.utf8.toBytes('qe$sg#oin*@Znm*X');
```

**Comment by Ruffio** [comment]
@LJC0915 if this issue has been resolved, then please close this issue. Thanks :-)
