### ISSUE TITLE
Is there auto-padding in CBC mode? (Answer: No, padding cannot safely be automatic)

### ISSUE THREAD

**Issue by realtergel** [ricmoo/aes-js#43]
support auto padding when plaintext is not a multiple of 16 bytes.

**Comment by gamelaster** [comment]
Exactly, I need to have Zero padding option on CBC ☹️ 
@johntergel Do you have a temporal solution?

**Comment by ricmoo** [comment]
Why do you need padding to be automatic? What padding type do you need? The library has PKCS#7 included... Cipher stealing is not implemented yet.

**Comment by ricmoo** [comment]
Oh, I realize now you meant you want to pad with zeros. You should probably use PKCS#7 instead, but otherwise you can just append 0 until it’s length is a multiple of 16.

**Comment by gamelaster** [comment]
@ricmoo What you mean by use PKCS#7?
I don't know why, but same code made in CryptoJS works, but in aes-js not. 
CryptoJS example (working): https://pastebin.com/C4SGtgiE
AES-JS example (not working): https://pastebin.com/9SA2S9iy

**Comment by albimcleod** [comment]
@gamelaster 

this worked for me

let extra = 16 - (text.length % 16);
        if (extra > 0) {
            text = pad(text.length + extra, text, ' ');
        }

**Comment by gamelaster** [comment]
@albimcleod not helped for me

**Comment by inf3rno** [comment]
Be aware of https://en.wikipedia.org/wiki/Padding_oracle_attack when doing this padding stuff! :-)

**Comment by ricmoo** [comment]
There are padding utilities available in aesjs, have you tried using those?

```javascript
> data = [ 0, 1, 2, 3 ]
[ 0, 1, 2, 3 ]
> data = aesjs.padding.pkcs7.pad(data)
Uint8Array [ 0, 1, 2, 3, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12 ]
> aesjs.padding.pkcs7.strip(data)
Uint8Array [ 0, 1, 2, 3 ]
```

Padding should not, in general, be automatic for AES libraries, because there are decisions at the application level that need to be aware of padding (if any).

**Comment by gamelaster** [comment]
@ricmoo Could you add Zero Padding? I posted a example between CryptoJS which works and AES-JS, which not working, and probably PKCS7 is not the right padding function

**Comment by ricmoo** [comment]
I will look into how the other libraries do this. Is there a standard for zero-padding?

The issue with simply adding zeros to the end until it is a multiple of 16 bytes long is that you won't know how many zeros to remove, so strip may be destructive to the original data.

For example, if the original data was [ 1, 2, 3, 4, 5, 0 ], after padding and stripping it would be [ 1, 2, 3, 4, 5 ].

The way to prevent this, would be to do what PKCS#7 does, and append an additional block of 0's if the input size is already a multiple of 16.

Can you provide some examples of zero-padded content? An example of 1 byte and 16 bytes is sufficient.

Please keep in mind with adding methods you may also be making yourself susceptible to Padding Oracle Attacks. Please read the article posted above by @inf3rno. Padding should not be taken lightly.

**Comment by ricmoo** [comment]
I'm going to close this now, without the intention of adding zero padding. If you can point to a standard that uses it, I'll re-consider, but I believe it is generally considered bad practice to use zero-padding.

Please feel free to re-open too, to continue discussion.

Thanks! :)
