### ISSUE TITLE
global "use strict" affects other plugins when combined into one js file

### ISSUE THREAD

**Issue by diegozhu** [ricmoo/aes-js#46]
fixed and pull request : https://github.com/ricmoo/aes-js/pull/45#issue-276268182

**Comment by Ruffio** [comment]
This issue should be closed as it has been fixed with the latest merge: https://github.com/ricmoo/aes-js/commit/0310eda25ee66fd9e3cf989a06cba297f9eda98a

**Comment by ricmoo** [comment]
The coffee shop I was in today blocked port 22, so I haven’t had a chance to publish to npm yet, so I’m leaving this open until I’ve had it is published.

**Comment by ricmoo** [comment]
It has now been published.
