### ISSUE TITLE
typescript: how import this?

### ISSUE THREAD

**Issue by haoqoo** [ricmoo/aes-js#48]
`import {aesjs} from 'aes-js';`

typescript, I use this way to import, but has error:

Uncaught (in promise): TypeError: Cannot read property 'utils' of undefined
TypeError: Cannot read property 'utils' of undefined

**Comment by tpetrina** [comment]
It is easy:

```tsx
var aesjs = require("aes-js")
```

**Comment by 0xDAEF0F** [comment]
`import * as aesjs from 'aes-js'`
