### ISSUE TITLE
Number of rounds are not enough

### ISSUE THREAD

**Issue by inf3rno** [ricmoo/aes-js#49]
https://www.schneier.com/blog/archives/2009/07/another_new_aes.html

**Comment by inf3rno** [comment]
Sadly these are the standard numbers for AES. Maybe I'll modify this lib for personal usage.

**Comment by ricmoo** [comment]
These attacks only affect very specific situations, so should in general, not be of huge concern to a properly designed system.

But yes, you can very much adjust the number of rounds in a custom version of this library, but keep in mind this will not be standards compliant, and you will need to re-write this library in any other language you wish to work with your modified version.
