### ISSUE TITLE
aesjs is not defined on amd

### ISSUE THREAD

**Issue by iBet7o** [ricmoo/aes-js#51]
I am integrating the service of a provider in magento2, the integration requires adding an external js file that contains the library aes-js and others. This external file marks me with the error "aesjs is not defined", I look in the code of this library and see

```javascript
} else if (typeof (define) === 'function' && define.amd) {
     define (aesjs);
```

What is the correct way to use aesjs with amd?

**Comment by ricmoo** [comment]
I will look into this. I do not use and myself, but will try to replicate this.

**Comment by Ruffio** [comment]
@ricmoo I think I have found the way to do it: https://www.devbridge.com/articles/understanding-amd-requirejs/

![image](https://user-images.githubusercontent.com/1877612/42408253-e3165666-81c9-11e8-8b7f-3c64f2e4d905.png)

**Comment by ricmoo** [comment]
I have updated the call to use the above format. Please let me know if there are still any issues, and feel free to re-open.

Thanks! :)
