### ISSUE TITLE
JSON.stringify(object) is not getting properly when decrypt

### ISSUE THREAD

**Issue by AkibDeraiya123** [ricmoo/aes-js#55]
Hello,
 I am using `Aes-js` module with my node.js development for encryption and decryption.
I'm trying to encrypt whole `Json (help of convert this object into stringify)`. Then i try to decrypt it and i also got that stringify object. But when i parse that decrypted string then it shows error like
 ```
SyntaxError: Unexpected token  in JSON at position 31
```

Here my node and npm version
```
Node:- v8.9.1
NPM:- 5.5.1
```

Here it is my code

```
var aesjs = require('aes-js');

var key = aesjs.utils.utf8.toBytes("39067A6F8088F81E9C2BB5D46A8C0F60");
var iv = aesjs.utils.utf8.toBytes("EFEF3C38B05F5871");

var text = JSON.stringify({username: 'abcd', password:'newPass'});

var textBytes = aesjs.padding.pkcs7.pad(aesjs.utils.utf8.toBytes(text));

var aesCbc = new aesjs.ModeOfOperation.cbc(key, iv);
var encryptedBytes = aesCbc.encrypt(textBytes);
 
var encryptedHex = aesjs.utils.hex.fromBytes(encryptedBytes);
console.log("data", encryptedHex); // HERE I GOT ENCRYPTED STRING OF STRINGIFY OBJECT
 
var encryptedBytes = aesjs.utils.hex.toBytes(encryptedHex);
 
var aesCbc = new aesjs.ModeOfOperation.cbc(key, iv);
var decryptedBytes = aesCbc.decrypt(aesjs.padding.pkcs7.pad(encryptedBytes));
 
var decryptedText = aesjs.utils.utf8.fromBytes(decryptedBytes);
console.log("decrypt", decryptedText);	
```

My decrypted string is print like ` {"username":"abcd","password":"newPass"}SjF咨偮!K㈎ `
And so that when i try to parse this string it will throw errors of invalid JSON position 

Please help me here.

I'm stuck in this. What's going wrong here or else please suggest me my mistake.

Thank you in advance.

**Comment by ricmoo** [comment]
You're close. :)

You need to unpad (i.e. strip) the decrypted text (you are re-padding the encrypted text):

```
// Replace this:
// var decryptedBytes = aesCbc.decrypt(aesjs.padding.pkcs7.pad(encryptedBytes));

// With this:
var decryptedBytes = aesjs.padding.pkcs7.strip(aesCbc.decrypt(encryptedBytes));
```

Hope this helps and let me know if you have any more issues. :)

**Comment by AkibDeraiya123** [comment]
Yes. This is working fine for me.

Thanks man @ricmoo. You are like a god. I was stuck on this issue from last 2 days. 

Thank you very much. :)

**Comment by ricmoo** [comment]
Glad it worked.

Thanks!
