### ISSUE TITLE
Initial Vector

### ISSUE THREAD

**Issue by WesVleuten** [ricmoo/aes-js#57]
Hi, I'd like to see initial vector implemented in this library. I don't know how to implement this myself but it would help immensely

**Comment by ricmoo** [comment]
Hey WesVleuten,

What do you mean?

All Mode of Operations that use initialization vectors fully support them; or maybe you are referring to something else?

**Comment by WesVleuten** [comment]
My bad, I'm an idiot. What I meant is fully implemented. Sorry to bother you! Thank you for your great work

**Comment by ricmoo** [comment]
LOL!

No worries. :)
