### ISSUE TITLE
Array contains invalid value

### ISSUE THREAD

**Issue by variyasandip** [ricmoo/aes-js#62]
I am implement 128 aes encrypt and decrypt on node-red using  node js .

i also mention the bellow function  getting an  error "Array contains invalid value"
 function decrypt128(crt_text){
			var key = aesjs.utils.utf8.toBytes(password)
        	        var encryptedHex =  crt_text;
			console.log("dynamic--------  " + crt_text);
			var encryptedBytes = aesjs.utils.hex.toBytes(encryptedHex);
			var aesEcb = new aesjs.ModeOfOperation.ecb(key);
			var decryptedBytes = aesEcb.decrypt(encryptedBytes);
			var decryptedText = aesjs.utils.utf8.fromBytes(decryptedBytes);
			return decryptedText;
        }
it is properly working i add to the  static var encryptedHex ="71149ac26898a42f6a6c8ddb9390f261" that is working fine. when i add dynamic value then got a error .

![n1](https://user-images.githubusercontent.com/40169201/41229955-9800f2ae-6d9b-11e8-8a7b-2d1b58fa342d.PNG)

Thanks

**Comment by Ruffio** [comment]
You have to describe what you are doing and what you expected. Create a demo that shows the issue.

**Comment by variyasandip** [comment]
do you know node-red server ?

i was create custom node using aes-js "aes128" decrypt node 

when i run that demo project got error "Array contains invalid value"  

function decrypt128(crt_text){
			var key = aesjs.utils.utf8.toBytes(password)
		    var encryptedHex =  crt_text; //"71149ac26898a42f6a6c8ddb9390f261"; //
			console.log("dynamic--------  " + crt_text);
			// When ready to decrypt the hex string, convert it back to bytes
			var encryptedBytes = aesjs.utils.hex.toBytes(encryptedHex);
			// Since electronic codebook does not store state, we can
			// reuse the same instance.
			var aesEcb = new aesjs.ModeOfOperation.ecb(key);
			var decryptedBytes = aesEcb.decrypt(encryptedBytes);
			// Convert our bytes back into text
			var decryptedText = aesjs.utils.utf8.fromBytes(decryptedBytes);
			return decryptedText;
        }

        //node specific code goes here
        var node = this;
        this.on('input', function(msg) {
            msg.payload = decrypt128(msg.payload);
            node.send(msg);
        });



 getting  an error in this line var decryptedBytes = aesEcb.decrypt(encryptedBytes);
