### ISSUE TITLE
invalid plaintext size (must be multiple of 16 bytes)

### ISSUE THREAD

**Issue by variyasandip** [ricmoo/aes-js#63]
Hello there 

I am using aes 128 (ECB) encrypt and decrypt function then got an error and my text minimum length 5 character . i mention bellow code and an error screen 
could  you please help me for that.
![1](https://user-images.githubusercontent.com/40169201/41451279-c14c3254-7089-11e8-83cd-36f0ba39b697.PNG)
![2](https://user-images.githubusercontent.com/40169201/41451285-c60a0fe6-7089-11e8-8e1d-954027ba5100.PNG)

**Comment by variyasandip** [comment]
i resolved this issue .

i was added  to  pkcs7pad(plaintext); on index.js file.then it was resolved issue i mention bellow screen
![3](https://user-images.githubusercontent.com/40169201/41455061-5d1c784c-7099-11e8-9688-23a2d306cd4d.PNG)

**Comment by hteinlinaung1423** [comment]
Hi @variyasandip  , i got the same issue and resolved it like you said. But decryption got extra unknown letter like this '' if my plain text is not multiple of 16. Is there any suggestion for decryption? I really appreciate you help.
