### ISSUE TITLE
Replace deprecated Buffer constructor

### ISSUE THREAD

**Issue by gabrielschulhof** [ricmoo/aes-js#68]
`new Buffer(...)` is deprecated and unsafe. Could `Buffer.from(...)` be used in [these places](https://github.com/ricmoo/aes-js/search?q=%22new+Buffer%22&unscoped_q=%22new+Buffer%22) instead?

**Comment by Ruffio** [comment]
IMHO I think it sounds as a good idea. Can you make a PR?
