### ISSUE TITLE
Removing padding on a, Decrypted Json Uint8Array, results in losing data

### ISSUE THREAD

**Issue by SupremeCookie** [ricmoo/aes-js#69]
I send decrypted data between a C# and Node.js application.
This means I decrypt the data in a format that is easily readable by both languages/implementation.
I chose to take a HexString.

I decrypt all data I send on a field, per field basis. Convert the decrypted byte[] into a HexString and send it to Node.

The thing is, when I try to decrypt a Json, turned byte array, turned hexstring back into json inside Node.Js whilst using the pkcs7 padding strip, I lose data of the Json.

When I don't use the pkcs7 strip function, the entire thing is properly decrypted without losing any data. Regardless of blocks size.

How come this happens?

Kind Regards,

SupremeCookie

**Comment by ricmoo** [comment]
You will probably want to use:

```javascript
var hexString = aesjs.utils.hex.fromBytes(bytes);
```

I will be overhauling this library soon, as it's been a while since it has been updated. I'll revisit what return types in input types are to make sure they are more consistent.

**Comment by SupremeCookie** [comment]
Hey Richard,

Thanks for the quick response.
I think my original request/issue wasn't clear enough.

What happens is that when I remove the padding from a byte array, that was
originally a json hexstring, it removes bytes that should not be removed.
If I don't allow the padding removal to happen, any sized json is valid,
regardless of ciperblock size.

Op di 4 sep. 2018 om 15:38 schreef Richard Moore <notifications@github.com>:

**Comment by Ruffio** [comment]
@SupremeCookie can this issue be closed?

**Comment by SupremeCookie** [comment]
The issue still stands, unfortunately I don't have the time to continue
looking into it. Sorry!
So you can close it.

Kind Regards,
SupremeCookie

Op vr 14 sep. 2018 om 08:38 schreef Rasmus Christiansen <
notifications@github.com>:

**Comment by ricmoo** [comment]
I will close this now, but if you can provide an example, I can look into it more. It should never strip more than 16 bytes, as invalid PKCS#7 padding will throw an exception...

Please feel free to re-open with sample input/output.

Thanks! :)
