### ISSUE TITLE
confuse with key generation

### ISSUE THREAD

**Issue by alexey-sh** [ricmoo/aes-js#71]
Hi,
thanks to the library.

I see the following in the readme:

> All keys must be 128 bits (16 bytes), 192 bits (24 bytes) or 256 bits (32 bytes) long.

> To generate keys from simple-to-remember passwords, consider using a password-based key-derivation function such as scrypt or bcrypt.

I see the following in [bcryptjs](https://github.com/dcodeIO/bcrypt.js#security-considerations) :

> The maximum input length is 72 bytes (note that UTF8 encoded characters use up to 4 bytes) and the length of generated hashes is 60 characters.

How can I use keys from bcrypt?

I tried
```
aesCtr = new aesjs.ModeOfOperation.ctr(aesjs.utils.utf8.toBytes(bcryptjs.hashSync('pass', 10)), new aesjs.Counter(5));
```

but it throws the following error:

```
index.js?63b3:205 Uncaught Error: invalid key size (must be 16, 24 or 32 bytes)
    at AES._prepare (index.js?63b3:205)
    at new AES (index.js?63b3:197)
    at new ModeOfOperationCTR (index.js?63b3:687)
```
Thanks.

**Comment by ricmoo** [comment]
I'm not very familiar with bcrypt, but it looks like it returns a string, so you could do:

```
aesCtr = new aesjs.ModeOfOperation.ctr(aesjs.utils.utf8.toBytes(bcryptjs.hashSync('pass', 10)).substring(0, 32), new aesjs.Counter(5));
```

The important part is the key must be either 16, 24 or 32 bytes. in the above example, I simply selected the first 32 bytes (with `.substring`) of the hash.

**Comment by alexey-sh** [comment]
@ricmoo thanks for the response.

Yes, bcryptjs returns a string. I'm just not sure about `.substring`. Is it safe to use for key?

**Comment by ricmoo** [comment]
I just looked into the output format of bcrypt, I completely take it back. Substring is **NOT safe**.

I’ll have to look more into this when I get home to a computer... it’s too hard to experiment on my phone. :)

It looks as though the bcrypt output includes all sorts of useful metadata, so we need to skip all that. Also, the key looks encoded, so we either need to decode it, or hash the encoded value.

**Comment by Ruffio** [comment]
Guys, please take a look at: https://en.wikipedia.org/wiki/Bcrypt

Brcrypt generates a string containing its parameters, salting value and the key:
![image](https://user-images.githubusercontent.com/1877612/45533834-478d9180-b7f9-11e8-91c0-822a4cded02d.png)

Use the key for your encryption/decryption.

**Comment by ricmoo** [comment]
Right, it looks like the key is 184 bit, and you need to actually parse the string. Do you have a method to extract the hash? You can use another hash function, like sha2-256 to get a 32 byte hash, or you could take a 128-bit slice.

**Comment by Ruffio** [comment]
Yup, personally I use these functions to get what I want, but I start with generation the IV:

> //Get salt value from hash
function GetSaltFromHash(hash) {
    return dcodeIO.bcrypt.getSalt(hash);
}

> //Get key from hash
function GetKeyFromHash(hash, iv) {
    return hash.replace(iv, '');
}

Btw. I think that questions about how to use bcrypt is a little off topic, they do have a good readme...

**Comment by Ruffio** [comment]
Shouldn't this 'issue' be closed?

**Comment by ricmoo** [comment]
I'm going to close this now, as I obviously have not looked into it for quite some time.

If you are using bcrypt, please read the library documentation on how to extract the key safely.

I generally recommend scrypt or argon2i, as PBKDF algorithms that have tuneable memory-hardness parameters provide a significantly more secure key. I just don't know enough about legacy bcrypt to provide sound advice.

**Comment by rosano** [comment]
I think it might be useful to have examples of key generation for the libraries recommended in the README. It took me a while to figure out how to integrate with scrypt and bcrypt so I'll post some minimalist working code here in case anyone finds it helpful (warning: might be totally bad usage!)

```javascript
const scrypt = require('scrypt-js');
const key = scrypt.syncScrypt(Buffer.from('password'.normalize('NFKC')), Buffer.from(Math.random().toString().normalize('NFKC')), 1024, 8, 1, 16);
const encrypted = aesjs.utils.hex.fromBytes((new aesjs.ModeOfOperation.ctr(key)).encrypt(aesjs.utils.utf8.toBytes('hello')));
const decrypted = aesjs.utils.utf8.fromBytes((new aesjs.ModeOfOperation.ctr(key)).decrypt(aesjs.utils.hex.toBytes(encrypted)));
console.log({ key, encrypted, decrypted });
```

```javascript
const bcrypt = require('bcryptjs');
const hash = bcrypt.hashSync('password');
const key = aesjs.utils.utf8.toBytes(hash.replace(bcrypt.getSalt(hash), ' '));
const encrypted = aesjs.utils.hex.fromBytes((new aesjs.ModeOfOperation.ctr(key)).encrypt(aesjs.utils.utf8.toBytes('hello')));
const decrypted = aesjs.utils.utf8.fromBytes((new aesjs.ModeOfOperation.ctr(key)).decrypt(aesjs.utils.hex.toBytes(encrypted)));
console.log({ hash, key, encrypted, decrypted });
```
