### ISSUE TITLE
Output size is 128 bits in CTR mode

### ISSUE THREAD

**Issue by adityanalge** [ricmoo/aes-js#72]
I believe in CTR mode, the output size should be equal to the input size. When I give a 16 byte key and a 32 byte input plain text, the output I receive is 64 bytes.

**Comment by ricmoo** [comment]
Are you padding using pkcs#7?

**Comment by ricmoo** [comment]
Actually, n/m. That would only result in 48 bytes. Can you provide an example?

**Comment by adityanalge** [comment]
I made a mistake. 
I used the `aesjs.utils.utf8.toBytes()` instead of the `aesjs.utils.hex.toBytes()` and thus misjudged my input size. 
I have fixed it now.
