### ISSUE TITLE
Remove test folder from published npm package

### ISSUE THREAD

**Issue by justinmeiners** [ricmoo/aes-js#78]
The test folder is more than a megabyte and projects that depend on the data do not need the tests.
Could you add the test folder to the .npmignore?

Thanks!

**Comment by ricmoo** [comment]
Yes, that makes a tonne of sense. I’ll get to it as soon as I can. :)

**Comment by justinmeiners** [comment]
@ricmoo Great! Thanks for being willing to do so.

**Comment by ricmoo** [comment]
I just checked and this is already the case. A fresh install using `npm install aes-js` provides a directory with only:

```
LICENSE.txt	README.md	bower.json	index.js	package.json
```

Are you sure you are using the latest version?

**Comment by justinmeiners** [comment]
No, im not. When I looked it was installed as a dependency of another. You can go ahead and close the issue.

**Comment by ricmoo** [comment]
Thanks. :)
