### ISSUE TITLE
CTR mode won't work without counter set

### ISSUE THREAD

**Issue by SpdyMx** [ricmoo/aes-js#9]
I have found an issue @line 584. There is the patch:

        if (counter === null || counter === undefined) {
            counter = new Counter()
        }

**Comment by ricmoo** [comment]
This is something I have thought about before, and mulled around in my brain-grapes. I think you are right and maybe we should have defaults for the counter (and possibly the other initialization vectors).

The main reason I haven't done so in the past, is it is very important to understand what these values are, how to choose them wisely, and when to store and broadcast them; for example, if the counter is always initialized to 0, and people don't think of initializing it themselves, it becomes dangerous to encrypt two different pieces of data with a the same secret key, as it can leak the secret key.

That said, most of (well, half?) the time I use these block ciphers libraries the keys are ephemeral anyways, randomly(ish) chosen, so in these cases the IV being set to a default is ok.

Let me think about it for a few more days. Maybe it is just a matter of beefing up documentation, then I'll feel better about including sane defaults. :)

Then the question becomes, which should be the default initial value for the `Counter`, 0 or 1.

Note to anyone else following, this would be a major version change.

**Comment by ricmoo** [comment]
I have fixed this now, in change https://github.com/ricmoo/aes-js/commit/907d9b93b6391023202de8f981db33b0fb4fe597.

Thanks @SpdyMx.
