### ISSUE TITLE
How to convert a string to key?

### ISSUE THREAD

**Issue by df257** [ricmoo/aes-js#99]
var str='acilddcgc87p85ic';
var textBytes  = aesjs.utils.utf8.toBytes(key);
var key = aesjs.padding.pkcs7.pad(textBytes);

this is right?

**Comment by df257** [comment]
server of java is use: AES/ECB/PKCS5Padding

**Comment by webdevelopland** [comment]
Wow, padding for a key is a bad idea.  
Try this: https://github.com/ricmoo/scrypt-js  
Or at least [sha](https://en.wikipedia.org/wiki/SHA-2)
